apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-local-pv
  labels:
    type: local
    func: nginx-vol
spec:
  storageClassName: base
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ycheng/nginx/webroot"
