apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  type: NodePort
  selector:
    func: nginx-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30002
      nodePort: 30001
